---
title: 'Class 6: R functions'
author: "Saeed Ghassemzadeh"
date: "4/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** R markdown document with my *code* and notes for the day. 

```{r}
plot(1:10, type = "l", col = "blue")
```


## Reading in files practice

```{r}
read.table("test1.txt", header = TRUE, sep = ",")
```

```{r}
read.csv("test1.txt")
```

```{r}
read.csv("test2.txt", sep = "$")
```

```{r}
read.csv("test3.txt", sep = "\t", header = FALSE, strip.white = TRUE)
```


```{r}
read.table("https://bioboot.github.io/bimm143_S19/class-material/test2.txt", sep = "$", header = TRUE)
```

# Functions

```{r}
add <- function(x, y=1){
  # The body!!
  x + y
}
```

```{r}
add(10)
```

```{r}
add(10, 10)
```

```{r}
add(c(1, 2, 3))
```

```{r}
add(c(1,2,3), 4)
```

```{r}
#add(1,2,3)
```

```{r}
#add(x=1, y="b")
```

### Another example

All functions have 
-Name
-Arguments
-Body

```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
# How would you get your function to work here...
rescale( c(1,2,NA,3,10) )
```

```{r}
# What should your function do here?
##rescale( c(1,10,"string") )
```

```{r}
x <- c(1,2,NA,3,10)
rng <- range(x, na.rm = TRUE)
(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale <- function(x) {
   rng <-range(x, na.rm = TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
   rng <-range(x, na.rm = na.rm)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2(c(1,2,NA,3,10))
```




```{r}
 rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
    rng <-range(x, na.rm=na.rm)
    print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   return(answer)
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
     print("please dont sing again")
   }
   print("I can see it in ...")
   return(answer)
}
```


```{r}
rescale3(c(1,3,NA,10))
```

```{r}
rescale3(c(1,3,NA,10), plot = TRUE)

```



